trigger:
  branches:
    include:
      - "main"

pool:

variables:
- name: 
  value:

stages:
  - stage: 
    jobs:
      - job: 
        steps:

        - task: DotNetCoreCLI@2
          inputs:
            command: 'restore'
            projects: 'IBMcode/IBMcode/IBMcode.csproj'
            feedsToUse: 'select'

        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: 'IBMcode/IBMcode/IBMcode.csproj'

        - task: DotNetCoreCLI@2
          inputs:
            command: 'test'
            projects: 'IBMcode/IBMcode/IBMcode.csproj'

        - task: DotNetCoreCLI@2
          inputs:
            command: 'publish'
            publishWebProjects: true

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'