trigger:
  branches:
    include:
      - "main"

pool: "ibmpool"

variables:
- name: BuildConfiguration
  value: Release

stages:
  - stage: Buildstage
    jobs:
      - job: buildjob
        steps:

        - task: DotNetCoreCLI@2
          displayName: dotnetrestore
          inputs:
            command: 'restore'
            projects: 'IBMcode/IBMcode/IBMcode.csproj'
            feedsToUse: 'select'

        - task: DotNetCoreCLI@2
          displayName: dotnetbuild
          inputs:
            command: 'build'
            projects: 'IBMcode/IBMcode/IBMcode.csproj'

        - task: DotNetCoreCLI@2
          displayName: dotnettest
          inputs:
            command: 'test'
            projects: 'IBMcode/IBMcode/IBMcode.csproj'

        - task: DotNetCoreCLI@2
          displayName: dotnetpublish
          inputs:
            command: 'publish'
            publishWebProjects: true

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'